INSERT INTO [dbo].[StagingEmployee]
           ([EmployeeId]
           ,[LastName]
           ,[FirstName]
           ,[Title]
           ,[ReportsTo]
           ,[BirthDate]
           ,[HireDate]
           ,[Address]
           ,[City]
           ,[State]
           ,[Country]
           ,[PostalCode]
           ,[Phone]
           ,[Fax]
           ,[Email])
    SELECT
           [EmployeeId]
           ,[LastName]
           ,[FirstName]
           ,[Title]
           ,[ReportsTo]
           ,[BirthDate]
           ,[HireDate]
           ,[Address]
           ,[City]
           ,[State]
           ,[Country]
           ,[PostalCode]
           ,[Phone]
           ,[Fax]
           ,[Email]
	FROM [Chinook].[dbo].[Employee]
GO

INSERT INTO [dbo].[StagingCustomer]
           ([CustomerId]
           ,[FirstName]
           ,[LastName]
           ,[Company]
           ,[Address]
           ,[City]
           ,[State]
           ,[Country]
           ,[PostalCode]
           ,[Phone]
           ,[Fax]
           ,[Email]
           ,[SupportRepId])
SELECT [CustomerId]
      ,[FirstName]
      ,[LastName]
      ,[Company]
      ,[Address]
      ,[City]
      ,[State]
      ,[Country]
      ,[PostalCode]
      ,[Phone]
      ,[Fax]
      ,[Email]
      ,[SupportRepId]
  FROM [Chinook].[dbo].[Customer]
GO


INSERT INTO [dbo].[StagingTrack]
           ([TrackId]
           ,[TrackName]
           ,[AlbumId]
           ,[GenreId]
           ,[Composer]
           ,[Milliseconds]
           ,[Bytes]
           ,[UnitPrice]
           ,[AlbumTitle]
           ,[ArtistId]
           ,[ArtistName]
           ,[GenreName]
           ,[MediaTypeId]
           ,[MediaTypeName])
     SELECT
           [TrackId]
           ,t.[Name]
           ,t.[AlbumId]
           ,t.[GenreId]
           ,[Composer]
           ,[Milliseconds]
           ,[Bytes]
           ,[UnitPrice]
           ,[Chinook].[dbo].[Album].[Title]
           ,[Chinook].[dbo].[Album].[ArtistId]
           ,[Chinook].[dbo].[Artist].[Name]
           ,[Chinook].[dbo].[Genre].[Name]
           ,[Chinook].[dbo].[MediaType].[MediaTypeId]
           ,[Chinook].[dbo].[MediaType].[Name]

	FROM [Chinook].[dbo].[Track] t 
	inner join [Chinook].[dbo].[Genre] On t.GenreId = [Chinook].[dbo].[Genre].[GenreId]
	inner join [Chinook].[dbo].[Album] On t.AlbumId = [Chinook].[dbo].[Album].[AlbumId]
	inner join [Chinook].[dbo].[Artist] On [Chinook].[dbo].[Album].ArtistId = [Chinook].[dbo].[Artist].[ArtistId]
	inner join [Chinook].[dbo].[MediaType] On t.MediaTypeId = [Chinook].[dbo].MediaType.[MediaTypeId]

GO

INSERT INTO [dbo].[StagingInvoices]
           ([InvoiceLineId]
           ,[InvoiceId]
           ,[TrackId]
           ,[UnitPrice]
           ,[Quantity]
           ,[CustomerId]
           ,[InvoiceDate]
           ,[BillingAddress]
           ,[BillingCity]
           ,[BillingState]
           ,[BillingCountry]
           ,[BillingPostalCode]
           ,[Total])
     SELECT
           [InvoiceLineId]
           ,[Chinook].[dbo].[Invoice].[InvoiceId]
           ,[TrackId]
           ,[UnitPrice]
           ,[Quantity]
           ,[CustomerId]
           ,[InvoiceDate]
           ,[BillingAddress]
           ,[BillingCity]
           ,[BillingState]
           ,[BillingCountry]
           ,[BillingPostalCode]
           ,[Total]
	FROM [Chinook].[dbo].[InvoiceLine]
		inner join [Chinook].[dbo].[Invoice] On [Chinook].[dbo].[Invoice].InvoiceId = [Chinook].[dbo].[InvoiceLine].InvoiceId
GO

INSERT INTO [dbo].[StagingPlaylist]
           ([PlaylistId]
           ,[TrackId]
           ,[Name])
     SELECT
          [Chinook].[dbo].[Playlist].[PlaylistId]
           ,[TrackId]
           ,[Name]
	FROM [Chinook].[dbo].[Playlist] 
		inner join [Chinook].[dbo].[PlaylistTrack] on [Chinook].[dbo].[PlaylistTrack].[PlaylistId] = [Chinook].[dbo].[Playlist].[PlaylistId]

GO

