{
  "name": "SemanticModel",
  "compatibilityLevel": 1400,
  "model": {
    "culture": "el-GR",
    "dataSources": [
      {
        "type": "structured",
        "name": "SQL/DESKTOP-MG0JNJB;ChinookDW",
        "connectionDetails": {
          "protocol": "tds",
          "address": {
            "server": "localhost",
            "database": "ChinookDW"
          },
          "authentication": null,
          "query": null
        },
        "options": {},
        "credential": {
          "AuthenticationKind": "Windows",
          "Username": "DESKTOP-MG0JNJB\\Pagonis",
          "EncryptConnection": true
        }
      }
    ],
    "tables": [
      {
        "name": "DimCustomer",
        "columns": [
          {
            "name": "CustomerKey",
            "dataType": "int64",
            "sourceColumn": "CustomerKey"
          },
          {
            "name": "CustomerId",
            "dataType": "int64",
            "sourceColumn": "CustomerId"
          },
          {
            "name": "FirstName",
            "dataType": "string",
            "sourceColumn": "FirstName"
          },
          {
            "name": "LastName",
            "dataType": "string",
            "sourceColumn": "LastName"
          },
          {
            "name": "Company",
            "dataType": "string",
            "sourceColumn": "Company"
          },
          {
            "name": "Address",
            "dataType": "string",
            "sourceColumn": "Address"
          },
          {
            "name": "City",
            "dataType": "string",
            "sourceColumn": "City"
          },
          {
            "name": "State",
            "dataType": "string",
            "sourceColumn": "State"
          },
          {
            "name": "Country",
            "dataType": "string",
            "sourceColumn": "Country"
          },
          {
            "name": "PostalCode",
            "dataType": "string",
            "sourceColumn": "PostalCode"
          },
          {
            "name": "Phone",
            "dataType": "string",
            "sourceColumn": "Phone"
          },
          {
            "name": "Fax",
            "dataType": "string",
            "sourceColumn": "Fax"
          },
          {
            "name": "Email",
            "dataType": "string",
            "sourceColumn": "Email"
          },
          {
            "name": "SupportRepId",
            "dataType": "int64",
            "sourceColumn": "SupportRepId"
          },
          {
            "name": "RowIsCurrent",
            "dataType": "int64",
            "sourceColumn": "RowIsCurrent"
          },
          {
            "name": "RowStartDate",
            "dataType": "dateTime",
            "sourceColumn": "RowStartDate"
          },
          {
            "name": "RowEndDate",
            "dataType": "dateTime",
            "sourceColumn": "RowEndDate"
          },
          {
            "name": "RowChangeReason",
            "dataType": "string",
            "sourceColumn": "RowChangeReason"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/DESKTOP-MG0JNJB;ChinookDW\",",
                "    dbo_DimCustomer = Source{[Schema=\"dbo\",Item=\"DimCustomer\"]}[Data]",
                "in",
                "    dbo_DimCustomer"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Customers'Countries",
            "expression": "DISTINCTCOUNT(DimCustomer[Country])"
          }
        ]
      },
      {
        "name": "DimDate",
        "columns": [
          {
            "name": "DateKey",
            "dataType": "int64",
            "sourceColumn": "DateKey"
          },
          {
            "name": "Date",
            "dataType": "dateTime",
            "sourceColumn": "Date"
          },
          {
            "name": "FullDateUK",
            "dataType": "string",
            "sourceColumn": "FullDateUK"
          },
          {
            "name": "FullDateUSA",
            "dataType": "string",
            "sourceColumn": "FullDateUSA"
          },
          {
            "name": "DayOfMonth",
            "dataType": "string",
            "sourceColumn": "DayOfMonth"
          },
          {
            "name": "DaySuffix",
            "dataType": "string",
            "sourceColumn": "DaySuffix"
          },
          {
            "name": "DayName",
            "dataType": "string",
            "sourceColumn": "DayName"
          },
          {
            "name": "DayOfWeekUSA",
            "dataType": "string",
            "sourceColumn": "DayOfWeekUSA"
          },
          {
            "name": "DayOfWeekUK",
            "dataType": "string",
            "sourceColumn": "DayOfWeekUK"
          },
          {
            "name": "DayOfWeekInMonth",
            "dataType": "string",
            "sourceColumn": "DayOfWeekInMonth"
          },
          {
            "name": "DayOfWeekInYear",
            "dataType": "string",
            "sourceColumn": "DayOfWeekInYear"
          },
          {
            "name": "DayOfQuarter",
            "dataType": "string",
            "sourceColumn": "DayOfQuarter"
          },
          {
            "name": "DayOfYear",
            "dataType": "string",
            "sourceColumn": "DayOfYear"
          },
          {
            "name": "WeekOfMonth",
            "dataType": "string",
            "sourceColumn": "WeekOfMonth"
          },
          {
            "name": "WeekOfQuarter",
            "dataType": "string",
            "sourceColumn": "WeekOfQuarter"
          },
          {
            "name": "WeekOfYear",
            "dataType": "string",
            "sourceColumn": "WeekOfYear"
          },
          {
            "name": "Month",
            "dataType": "string",
            "sourceColumn": "Month"
          },
          {
            "name": "MonthName",
            "dataType": "string",
            "sourceColumn": "MonthName"
          },
          {
            "name": "MonthOfQuarter",
            "dataType": "string",
            "sourceColumn": "MonthOfQuarter"
          },
          {
            "name": "Quarter",
            "dataType": "string",
            "sourceColumn": "Quarter"
          },
          {
            "name": "QuarterName",
            "dataType": "string",
            "sourceColumn": "QuarterName"
          },
          {
            "name": "Year",
            "dataType": "string",
            "sourceColumn": "Year"
          },
          {
            "name": "YearName",
            "dataType": "string",
            "sourceColumn": "YearName"
          },
          {
            "name": "MonthYear",
            "dataType": "string",
            "sourceColumn": "MonthYear"
          },
          {
            "name": "MMYYYY",
            "dataType": "string",
            "sourceColumn": "MMYYYY"
          },
          {
            "name": "FirstDayOfMonth",
            "dataType": "dateTime",
            "sourceColumn": "FirstDayOfMonth"
          },
          {
            "name": "LastDayOfMonth",
            "dataType": "dateTime",
            "sourceColumn": "LastDayOfMonth"
          },
          {
            "name": "FirstDayOfQuarter",
            "dataType": "dateTime",
            "sourceColumn": "FirstDayOfQuarter"
          },
          {
            "name": "LastDayOfQuarter",
            "dataType": "dateTime",
            "sourceColumn": "LastDayOfQuarter"
          },
          {
            "name": "FirstDayOfYear",
            "dataType": "dateTime",
            "sourceColumn": "FirstDayOfYear"
          },
          {
            "name": "LastDayOfYear",
            "dataType": "dateTime",
            "sourceColumn": "LastDayOfYear"
          },
          {
            "name": "IsHolidayUSA",
            "dataType": "boolean",
            "sourceColumn": "IsHolidayUSA"
          },
          {
            "name": "IsWeekday",
            "dataType": "boolean",
            "sourceColumn": "IsWeekday"
          },
          {
            "name": "HolidayUSA",
            "dataType": "string",
            "sourceColumn": "HolidayUSA"
          },
          {
            "name": "IsHolidayUK",
            "dataType": "boolean",
            "sourceColumn": "IsHolidayUK"
          },
          {
            "name": "HolidayUK",
            "dataType": "string",
            "sourceColumn": "HolidayUK"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/DESKTOP-MG0JNJB;ChinookDW\",",
                "    dbo_DimDate = Source{[Schema=\"dbo\",Item=\"DimDate\"]}[Data]",
                "in",
                "    dbo_DimDate"
              ]
            }
          }
        ]
      },
      {
        "name": "DimEmployee",
        "columns": [
          {
            "name": "EmployeeId",
            "dataType": "int64",
            "sourceColumn": "EmployeeId"
          },
          {
            "name": "LastName",
            "dataType": "string",
            "sourceColumn": "LastName"
          },
          {
            "name": "FirstName",
            "dataType": "string",
            "sourceColumn": "FirstName"
          },
          {
            "name": "Title",
            "dataType": "string",
            "sourceColumn": "Title"
          },
          {
            "name": "ReportsTo",
            "dataType": "int64",
            "sourceColumn": "ReportsTo"
          },
          {
            "name": "BirthDate",
            "dataType": "dateTime",
            "sourceColumn": "BirthDate"
          },
          {
            "name": "HireDate",
            "dataType": "dateTime",
            "sourceColumn": "HireDate"
          },
          {
            "name": "Address",
            "dataType": "string",
            "sourceColumn": "Address"
          },
          {
            "name": "City",
            "dataType": "string",
            "sourceColumn": "City"
          },
          {
            "name": "State",
            "dataType": "string",
            "sourceColumn": "State"
          },
          {
            "name": "Country",
            "dataType": "string",
            "sourceColumn": "Country"
          },
          {
            "name": "PostalCode",
            "dataType": "string",
            "sourceColumn": "PostalCode"
          },
          {
            "name": "Phone",
            "dataType": "string",
            "sourceColumn": "Phone"
          },
          {
            "name": "Fax",
            "dataType": "string",
            "sourceColumn": "Fax"
          },
          {
            "name": "Email",
            "dataType": "string",
            "sourceColumn": "Email"
          },
          {
            "name": "RowIsCurrent",
            "dataType": "int64",
            "sourceColumn": "RowIsCurrent"
          },
          {
            "name": "RowStartDate",
            "dataType": "dateTime",
            "sourceColumn": "RowStartDate"
          },
          {
            "name": "RowEndDate",
            "dataType": "dateTime",
            "sourceColumn": "RowEndDate"
          },
          {
            "name": "RowChangeReason",
            "dataType": "string",
            "sourceColumn": "RowChangeReason"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/DESKTOP-MG0JNJB;ChinookDW\",",
                "    dbo_DimEmployee = Source{[Schema=\"dbo\",Item=\"DimEmployee\"]}[Data]",
                "in",
                "    dbo_DimEmployee"
              ]
            }
          }
        ]
      },
      {
        "name": "DimPlaylist",
        "columns": [
          {
            "name": "PlaylistId",
            "dataType": "int64",
            "sourceColumn": "PlaylistId"
          },
          {
            "name": "TrackId",
            "dataType": "int64",
            "sourceColumn": "TrackId"
          },
          {
            "name": "Name",
            "dataType": "string",
            "sourceColumn": "Name"
          },
          {
            "name": "RowIsCurrent",
            "dataType": "int64",
            "sourceColumn": "RowIsCurrent"
          },
          {
            "name": "RowStartDate",
            "dataType": "dateTime",
            "sourceColumn": "RowStartDate"
          },
          {
            "name": "RowEndDate",
            "dataType": "dateTime",
            "sourceColumn": "RowEndDate"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/DESKTOP-MG0JNJB;ChinookDW\",",
                "    dbo_DimPlaylist = Source{[Schema=\"dbo\",Item=\"DimPlaylist\"]}[Data],",
                "    #\"Removed Columns\" = Table.RemoveColumns(dbo_DimPlaylist,{\"RowChangeReason\"})",
                "in",
                "    #\"Removed Columns\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "NumberOfGenres",
            "expression": "DISTINCTCOUNT(DimTrack[GenreName])"
          }
        ]
      },
      {
        "name": "DimTrack",
        "columns": [
          {
            "name": "TrackId",
            "dataType": "int64",
            "sourceColumn": "TrackId"
          },
          {
            "name": "TrackName",
            "dataType": "string",
            "sourceColumn": "TrackName"
          },
          {
            "name": "AlbumId",
            "dataType": "int64",
            "sourceColumn": "AlbumId"
          },
          {
            "name": "GenreId",
            "dataType": "int64",
            "sourceColumn": "GenreId"
          },
          {
            "name": "Composer",
            "dataType": "string",
            "sourceColumn": "Composer"
          },
          {
            "name": "Milliseconds",
            "dataType": "int64",
            "sourceColumn": "Milliseconds"
          },
          {
            "name": "Bytes",
            "dataType": "int64",
            "sourceColumn": "Bytes"
          },
          {
            "name": "UnitPrice",
            "dataType": "double",
            "sourceColumn": "UnitPrice"
          },
          {
            "name": "AlbumTitle",
            "dataType": "string",
            "sourceColumn": "AlbumTitle"
          },
          {
            "name": "ArtistId",
            "dataType": "int64",
            "sourceColumn": "ArtistId"
          },
          {
            "name": "ArtistName",
            "dataType": "string",
            "sourceColumn": "ArtistName"
          },
          {
            "name": "GenreName",
            "dataType": "string",
            "sourceColumn": "GenreName"
          },
          {
            "name": "MediaTypeId",
            "dataType": "int64",
            "sourceColumn": "MediaTypeId"
          },
          {
            "name": "MediaTypeName",
            "dataType": "string",
            "sourceColumn": "MediaTypeName"
          },
          {
            "name": "RowIsCurrent",
            "dataType": "int64",
            "sourceColumn": "RowIsCurrent"
          },
          {
            "name": "RowStartDate",
            "dataType": "dateTime",
            "sourceColumn": "RowStartDate"
          },
          {
            "name": "RowEndDate",
            "dataType": "dateTime",
            "sourceColumn": "RowEndDate"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/DESKTOP-MG0JNJB;ChinookDW\",",
                "    dbo_DimTrack = Source{[Schema=\"dbo\",Item=\"DimTrack\"]}[Data],",
                "    #\"Removed Columns\" = Table.RemoveColumns(dbo_DimTrack,{\"RowChangeReason\"})",
                "in",
                "    #\"Removed Columns\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "TrackTimeInMinutes",
            "expression": "DIVIDE(CALCULATE(SUM(DimTrack[Milliseconds]) , FactInvoices[CustomerKey]) , 60000)"
          }
        ]
      },
      {
        "name": "FactInvoices",
        "columns": [
          {
            "name": "InvoiceLineId",
            "dataType": "int64",
            "sourceColumn": "InvoiceLineId"
          },
          {
            "name": "InvoiceId",
            "dataType": "int64",
            "sourceColumn": "InvoiceId"
          },
          {
            "name": "TrackId",
            "dataType": "int64",
            "sourceColumn": "TrackId"
          },
          {
            "name": "UnitPrice",
            "dataType": "double",
            "sourceColumn": "UnitPrice",
            "formatString": "#,0.00 \"€\";-#,0.00 \"€\";#,0.00 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\" ThousandSeparator=\"True\"><Currency LCID=\"1032\" DisplayName=\"€ Greek (Greece)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "Quantity",
            "dataType": "int64",
            "sourceColumn": "Quantity"
          },
          {
            "name": "CustomerKey",
            "dataType": "int64",
            "sourceColumn": "CustomerKey"
          },
          {
            "name": "InvoiceDateKey",
            "dataType": "int64",
            "sourceColumn": "InvoiceDateKey"
          },
          {
            "name": "BillingAddress",
            "dataType": "string",
            "sourceColumn": "BillingAddress"
          },
          {
            "name": "BillingCity",
            "dataType": "string",
            "sourceColumn": "BillingCity"
          },
          {
            "name": "BillingState",
            "dataType": "string",
            "sourceColumn": "BillingState"
          },
          {
            "name": "BillingCountry",
            "dataType": "string",
            "sourceColumn": "BillingCountry"
          },
          {
            "name": "BillingPostalCode",
            "dataType": "string",
            "sourceColumn": "BillingPostalCode"
          },
          {
            "name": "Total",
            "dataType": "decimal",
            "sourceColumn": "Total",
            "formatString": "#,0.00 \"€\";-#,0.00 \"€\";#,0.00 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\" ThousandSeparator=\"True\"><Currency LCID=\"1032\" DisplayName=\"€ Greek (Greece)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "RowIsCurrent",
            "dataType": "int64",
            "sourceColumn": "RowIsCurrent"
          },
          {
            "name": "RowStartDate",
            "dataType": "dateTime",
            "sourceColumn": "RowStartDate"
          },
          {
            "name": "RowEndDate",
            "dataType": "dateTime",
            "sourceColumn": "RowEndDate"
          },
          {
            "type": "calculated",
            "name": "Continent",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": [
              "IF(FactInvoices[BillingCountry] = \"Argentina\" || FactInvoices[BillingCountry] = \"Brazil\" || FactInvoices[BillingCountry] =  \" USA\" || FactInvoices[BillingCountry] =\"Chile\"  ||FactInvoices[BillingCountry] = \"Canada\" , \"America\" ,",
              "",
              "     IF(FactInvoices[BillingCountry] = \"Australia\" , \"Australia\",",
              "",
              "     IF(FactInvoices[BillingCountry]= \"India\", \"India\" ,\"Europe\"",
              "",
              ")))"
            ]
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/DESKTOP-MG0JNJB;ChinookDW\",",
                "    dbo_FactInvoices = Source{[Schema=\"dbo\",Item=\"FactInvoices\"]}[Data],",
                "    #\"Removed Columns\" = Table.RemoveColumns(dbo_FactInvoices,{\"RowChangeReason\"})",
                "in",
                "    #\"Removed Columns\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "TotalAmountOfPurchases",
            "expression": "CALCULATE(SUM(FactInvoices[Total]))",
            "formatString": "#,0.00 \"€\";-#,0.00 \"€\";#,0.00 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"1032\" DisplayName=\"€ Greek (Greece)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "AverageUnitPrice",
            "expression": "AVERAGE(FactInvoices[UnitPrice])",
            "formatString": "#,0.00 \"€\";-#,0.00 \"€\";#,0.00 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"1032\" DisplayName=\"€ Greek (Greece)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "MaxPrice",
            "expression": "MAX(FactInvoices[UnitPrice])",
            "formatString": "#,0.00 \"€\";-#,0.00 \"€\";#,0.00 \"€\"",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"1032\" DisplayName=\"€ Greek (Greece)\" Symbol=\"€\" PositivePattern=\"3\" NegativePattern=\"8\" /></Format>"
              }
            ]
          },
          {
            "name": "MinPrice",
            "expression": "MIN(FactInvoices[UnitPrice])"
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "1d04ace5-0d94-4fdd-804a-39463bb9dfaa",
        "fromTable": "FactInvoices",
        "fromColumn": "CustomerKey",
        "toTable": "DimCustomer",
        "toColumn": "CustomerKey"
      },
      {
        "name": "cdd787c6-4a58-4eb4-bcee-252e9c9f33ea",
        "fromTable": "FactInvoices",
        "fromColumn": "TrackId",
        "toTable": "DimTrack",
        "toColumn": "TrackId"
      },
      {
        "name": "36f7fb33-37f1-417c-a932-ff0c00090069",
        "fromTable": "DimPlaylist",
        "fromColumn": "TrackId",
        "toTable": "DimTrack",
        "toColumn": "TrackId"
      },
      {
        "name": "c01fbf6e-9c7e-4426-b8da-d69f3936dee6",
        "fromTable": "DimCustomer",
        "fromColumn": "SupportRepId",
        "toTable": "DimEmployee",
        "toColumn": "EmployeeId"
      },
      {
        "name": "0a87f795-72f6-484d-bfea-39425f4c9cd2",
        "fromTable": "FactInvoices",
        "fromColumn": "InvoiceDateKey",
        "toTable": "DimDate",
        "toColumn": "DateKey"
      }
    ],
    "annotations": [
      {
        "name": "ClientCompatibilityLevel",
        "value": "500"
      }
    ]
  },
  "id": "SemanticModel"
}